/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RabbitId = IDL.Text;
export const CollectorId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const Rarity = IDL.Variant({
  'rare' : IDL.Null,
  'unique' : IDL.Null,
  'common' : IDL.Null,
});
export const Coordinates = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const RabbitStatus = IDL.Variant({
  'pending_activation' : IDL.Null,
  'for_sale' : IDL.Null,
  'auction' : IDL.Null,
  'in_collection' : IDL.Null,
});
export const Price = IDL.Nat;
export const Rabbit = IDL.Record({
  'id' : RabbitId,
  'status' : RabbitStatus,
  'birthDate' : Timestamp,
  'owner' : IDL.Opt(CollectorId),
  'name' : IDL.Text,
  'likes' : IDL.Nat,
  'materials' : IDL.Text,
  'rarity' : Rarity,
  'photo' : IDL.Opt(ExternalBlob),
  'price' : IDL.Opt(Price),
  'coordinates' : Coordinates,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'status' : IDL.Text,
  'content' : IDL.Text,
  'recipient' : CollectorId,
  'sender' : CollectorId,
  'timestamp' : Timestamp,
});
export const CollectorProfile = IDL.Record({
  'id' : IDL.Text,
  'nickname' : IDL.Text,
  'city' : IDL.Text,
  'rabbitsCollected' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateRabbit' : IDL.Func([RabbitId, CollectorId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyRabbit' : IDL.Func([RabbitId, CollectorId, IDL.Nat], [], []),
  'completeAuction' : IDL.Func([RabbitId, CollectorId], [], []),
  'createCollectorProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'createRabbit' : IDL.Func(
      [
        RabbitId,
        IDL.Text,
        Timestamp,
        IDL.Text,
        Rarity,
        Coordinates,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'getAllRabbits' : IDL.Func([], [IDL.Vec(Rabbit)], ['query']),
  'getAvailableRabbits' : IDL.Func([], [IDL.Vec(Rabbit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectorMessages' : IDL.Func(
      [CollectorId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCollectorProfileById' : IDL.Func(
      [CollectorId],
      [IDL.Opt(CollectorProfile)],
      ['query'],
    ),
  'getCollectorRabbits' : IDL.Func([CollectorId], [IDL.Vec(Rabbit)], ['query']),
  'getRabbitById' : IDL.Func([RabbitId], [IDL.Opt(Rabbit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeRabbit' : IDL.Func([RabbitId], [], []),
  'placeBid' : IDL.Func([RabbitId, CollectorId, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [CollectorId, CollectorId, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateRabbitForSale' : IDL.Func([RabbitId, IDL.Nat], [], []),
  'updateRabbitInAuction' : IDL.Func([RabbitId, IDL.Nat, IDL.Int], [], []),
  'updateRabbitMaterials' : IDL.Func([RabbitId, IDL.Text], [], []),
  'updateRabbitName' : IDL.Func([RabbitId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RabbitId = IDL.Text;
  const CollectorId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const Rarity = IDL.Variant({
    'rare' : IDL.Null,
    'unique' : IDL.Null,
    'common' : IDL.Null,
  });
  const Coordinates = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const RabbitStatus = IDL.Variant({
    'pending_activation' : IDL.Null,
    'for_sale' : IDL.Null,
    'auction' : IDL.Null,
    'in_collection' : IDL.Null,
  });
  const Price = IDL.Nat;
  const Rabbit = IDL.Record({
    'id' : RabbitId,
    'status' : RabbitStatus,
    'birthDate' : Timestamp,
    'owner' : IDL.Opt(CollectorId),
    'name' : IDL.Text,
    'likes' : IDL.Nat,
    'materials' : IDL.Text,
    'rarity' : Rarity,
    'photo' : IDL.Opt(ExternalBlob),
    'price' : IDL.Opt(Price),
    'coordinates' : Coordinates,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'status' : IDL.Text,
    'content' : IDL.Text,
    'recipient' : CollectorId,
    'sender' : CollectorId,
    'timestamp' : Timestamp,
  });
  const CollectorProfile = IDL.Record({
    'id' : IDL.Text,
    'nickname' : IDL.Text,
    'city' : IDL.Text,
    'rabbitsCollected' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateRabbit' : IDL.Func([RabbitId, CollectorId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyRabbit' : IDL.Func([RabbitId, CollectorId, IDL.Nat], [], []),
    'completeAuction' : IDL.Func([RabbitId, CollectorId], [], []),
    'createCollectorProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'createRabbit' : IDL.Func(
        [
          RabbitId,
          IDL.Text,
          Timestamp,
          IDL.Text,
          Rarity,
          Coordinates,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'getAllRabbits' : IDL.Func([], [IDL.Vec(Rabbit)], ['query']),
    'getAvailableRabbits' : IDL.Func([], [IDL.Vec(Rabbit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectorMessages' : IDL.Func(
        [CollectorId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCollectorProfileById' : IDL.Func(
        [CollectorId],
        [IDL.Opt(CollectorProfile)],
        ['query'],
      ),
    'getCollectorRabbits' : IDL.Func(
        [CollectorId],
        [IDL.Vec(Rabbit)],
        ['query'],
      ),
    'getRabbitById' : IDL.Func([RabbitId], [IDL.Opt(Rabbit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeRabbit' : IDL.Func([RabbitId], [], []),
    'placeBid' : IDL.Func([RabbitId, CollectorId, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [CollectorId, CollectorId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateRabbitForSale' : IDL.Func([RabbitId, IDL.Nat], [], []),
    'updateRabbitInAuction' : IDL.Func([RabbitId, IDL.Nat, IDL.Int], [], []),
    'updateRabbitMaterials' : IDL.Func([RabbitId, IDL.Text], [], []),
    'updateRabbitName' : IDL.Func([RabbitId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };