/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CollectorId = string;
export interface CollectorProfile {
  'id' : string,
  'nickname' : string,
  'city' : string,
  'rabbitsCollected' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface Coordinates { 'x' : number, 'y' : number }
export type ExternalBlob = Uint8Array;
export interface Message {
  'status' : string,
  'content' : string,
  'recipient' : CollectorId,
  'sender' : CollectorId,
  'timestamp' : Timestamp,
}
export type Price = bigint;
export interface Rabbit {
  'id' : RabbitId,
  'status' : RabbitStatus,
  'birthDate' : Timestamp,
  'owner' : [] | [CollectorId],
  'name' : string,
  'likes' : bigint,
  'materials' : string,
  'rarity' : Rarity,
  'photo' : [] | [ExternalBlob],
  'price' : [] | [Price],
  'coordinates' : Coordinates,
}
export type RabbitId = string;
export type RabbitStatus = { 'pending_activation' : null } |
  { 'for_sale' : null } |
  { 'auction' : null } |
  { 'in_collection' : null };
export type Rarity = { 'rare' : null } |
  { 'unique' : null } |
  { 'common' : null };
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateRabbit' : ActorMethod<[RabbitId, CollectorId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyRabbit' : ActorMethod<[RabbitId, CollectorId, bigint], undefined>,
  'completeAuction' : ActorMethod<[RabbitId, CollectorId], undefined>,
  'createCollectorProfile' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'createRabbit' : ActorMethod<
    [
      RabbitId,
      string,
      Timestamp,
      string,
      Rarity,
      Coordinates,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'getAllRabbits' : ActorMethod<[], Array<Rabbit>>,
  'getAvailableRabbits' : ActorMethod<[], Array<Rabbit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectorMessages' : ActorMethod<[CollectorId], Array<Message>>,
  'getCollectorProfileById' : ActorMethod<
    [CollectorId],
    [] | [CollectorProfile]
  >,
  'getCollectorRabbits' : ActorMethod<[CollectorId], Array<Rabbit>>,
  'getRabbitById' : ActorMethod<[RabbitId], [] | [Rabbit]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeRabbit' : ActorMethod<[RabbitId], undefined>,
  'placeBid' : ActorMethod<[RabbitId, CollectorId, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [CollectorId, CollectorId, string, string],
    undefined
  >,
  'updateRabbitForSale' : ActorMethod<[RabbitId, bigint], undefined>,
  'updateRabbitInAuction' : ActorMethod<[RabbitId, bigint, bigint], undefined>,
  'updateRabbitMaterials' : ActorMethod<[RabbitId, string], undefined>,
  'updateRabbitName' : ActorMethod<[RabbitId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];